### PR TITLE
Fix Ubuntu

### LINKED ISSUE #30: Ubuntu family is "not supported"
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.4.0
- Ruby:  2.4.3p205
- Distribution: Ubuntu 16.04
- Module version: 2.0.1

## How to reproduce (e.g Puppet code you use)
In puppet code a block that contains:

```include ::openvmtools```

In hiera:
```
openvmtools::ensure: present
openvmtools::autoupgrade: false
openvmtools::uninstall_vmware_tools: false
```

## What are you seeing

open-vm-tools should be installed

## What behaviour did you expect instead

open-vm-tools is not installed

## Output log

2020-05-07 09:38:26,122 INFO  [qtp605093187-80149] [puppetserver] Scope(Class[Openvmtools]) Your operating system Ubuntu is unsupported and will not have the Open Virtual Machine Tools installed.

## Any additional information you'd like to impart
The hiera.yml includes this one: 
```
hierarchy:
  - name: 'OS Major Version'
    path: '%{facts.os.family}.%{facts.os.name}.%{facts.os.release.major}.yaml'
  - name: 'OS Name'
    path: '%{facts.os.family}.%{facts.os.name}.yaml'
  - name: 'OS Family'
    path: '%{facts.os.family}.yaml'
```

In Ubuntu 16 the facts returns this:
```
os
  family => "Debian",
  name => "Ubuntu",
  release => {
    full => "16.04",
    major => "16.04"
```
Release major is "16.04", but the yaml filename is "Debian.Ubuntu.16.yaml", then never matches and reports the os as unsupported. The filename should be "Debian.Ubuntu.16.04.yaml".

### PR DESCRIPTION
**Pull request by ghoneycutt**
Without this patch, hiera will never match against Ubuntu systems as the
major release contains the '.04'

Fixes #30

### CODE REVIEW

**Comment by ghoneycutt** [comment]
https://github.com/camptocamp/facterdb/blob/master/facts/3.14/ubuntu-18.04-x86_64.facts#L325 shows that `os.release.major` contains the `.04` which is why Ubuntu was not working.

File: spec/classes/openvmtools_init_spec.rb [hunk 1]
```diff
@@ -143,20 +143,19 @@
...
         operatingsystem:           'Ubuntu',
-        operatingsystemmajrelease: '14',
+        operatingsystemmajrelease: '14.04',
         operatingsystemrelease:    '14.04',
         os:                        {
           family:  'Debian',
           name:    'Ubuntu',
           release: {
             full:  '14.04',
-            major: '14',
```
Comment (ghoneycutt) [inline spec/classes/openvmtools_init_spec.rb:158]: You can verify at https://github.com/camptocamp/facterdb/blob/master/facts/3.14/ubuntu-14.04-x86_64.facts#L336-L339

**Review by kenyon — APPROVED** [review]
